# Generated by Django 2.1.7 on 2019-02-14 10:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20190210_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='address',
            field=models.TextField(blank=True, max_length=512, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='ключ подтверждения'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 10, 29, 56, 399372, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
